import express from "express";

import CORS from 'cors'

const app = express();
 app.use(CORS);

const port = process.env.PORT || 3000;

app.get("/", (req, res) => {
  res.send("Hello api for data!!");
});

app.get("/api/jobs", (req, res) => {
  const demoJobs = [
    // --- Web/Frontend/Full Stack/Backend/AI/Data/Cloud/Other ---
    {
      employer_name: "Tata Consultancy Services",
      employer_logo: "",
      employer_website: "https://www.tcs.com",
      job_city: "Mumbai",
      job_employment_types: ["Full-time"],
      job_description:
        "Frontend Developer (React.js, TypeScript) for enterprise web apps.",
      job_apply_link: "https://www.tcs.com/careers",
    },
    {
      employer_name: "Infosys",
      employer_logo: "",
      employer_website: "https://www.infosys.com",
      job_city: "Bangalore",
      job_employment_types: ["Full-time"],
      job_description:
        "Full Stack Developer (Node.js, React, MongoDB) for fintech projects.",
      job_apply_link: "https://www.infosys.com/careers",
    },
    {
      employer_name: "Wipro",
      employer_logo: "",
      employer_website: "https://www.wipro.com",
      job_city: "Hyderabad",
      job_employment_types: ["Full-time"],
      job_description:
        "Backend Developer (Python/Django, REST APIs) for healthcare platform.",
      job_apply_link: "https://careers.wipro.com",
    },
    {
      employer_name: "HCLTech",
      employer_logo: "",
      employer_website: "https://www.hcltech.com",
      job_city: "Noida",
      job_employment_types: ["Full-time"],
      job_description:
        "AI Developer (TensorFlow, NLP, LLMs) for automation solutions.",
      job_apply_link: "https://www.hcltech.com/careers",
    },
    {
      employer_name: "Accenture",
      employer_logo: "",
      employer_website: "https://www.accenture.com",
      job_city: "Pune",
      job_employment_types: ["Full-time"],
      job_description:
        "Data Analyst (SQL, Power BI, Python) for analytics team.",
      job_apply_link: "https://www.accenture.com/in-en/careers",
    },
    {
      employer_name: "Flipkart",
      employer_logo: "",
      employer_website: "https://www.flipkart.com",
      job_city: "Bangalore",
      job_employment_types: ["Full-time"],
      job_description:
        "Web Developer (Vue.js, HTML, CSS) for e-commerce platform.",
      job_apply_link: "https://www.flipkartcareers.com",
    },
    {
      employer_name: "Amazon India",
      employer_logo: "",
      employer_website: "https://www.amazon.jobs/en/locations/india",
      job_city: "Hyderabad",
      job_employment_types: ["Full-time"],
      job_description: "Cloud Engineer (AWS, DevOps, Docker, Kubernetes).",
      job_apply_link: "https://www.amazon.jobs/en/locations/india",
    },
    {
      employer_name: "BYJU'S",
      employer_logo: "",
      employer_website: "https://byjus.com",
      job_city: "Bangalore",
      job_employment_types: ["Full-time"],
      job_description:
        "Backend Developer (Java, Spring Boot, MySQL) for EdTech.",
      job_apply_link: "https://careers.byjus.com",
    },
    {
      employer_name: "Zomato",
      employer_logo: "",
      employer_website: "https://www.zomato.com/careers",
      job_city: "Gurgaon",
      job_employment_types: ["Full-time"],
      job_description:
        "Full Stack Developer (MERN stack) for food delivery platform.",
      job_apply_link: "https://www.zomato.com/careers",
    },
    {
      employer_name: "Paytm",
      employer_logo: "",
      employer_website: "https://paytm.com/careers",
      job_city: "Noida",
      job_employment_types: ["Full-time"],
      job_description:
        "Android Developer (Kotlin, Jetpack Compose) for payments app.",
      job_apply_link: "https://paytm.com/careers",
    },
    {
      employer_name: "Ola Cabs",
      employer_logo: "",
      employer_website: "https://careers.olacabs.com",
      job_city: "Bangalore",
      job_employment_types: ["Full-time"],
      job_description: "DevOps Engineer (CI/CD, AWS, Docker, Terraform).",
      job_apply_link: "https://careers.olacabs.com",
    },
    {
      employer_name: "Reliance Jio",
      employer_logo: "",
      employer_website: "https://careers.jio.com",
      job_city: "Mumbai",
      job_employment_types: ["Full-time"],
      job_description:
        "Network Security Engineer (Firewall, Cloud Security, CCNP).",
      job_apply_link: "https://careers.jio.com",
    },
    {
      employer_name: "Freshworks",
      employer_logo: "",
      employer_website: "https://www.freshworks.com/careers",
      job_city: "Chennai",
      job_employment_types: ["Full-time"],
      job_description:
        "QA Automation Engineer (Selenium, Cypress, API Testing).",
      job_apply_link: "https://www.freshworks.com/careers",
    },
    {
      employer_name: "Swiggy",
      employer_logo: "",
      employer_website: "https://careers.swiggy.com",
      job_city: "Bangalore",
      job_employment_types: ["Full-time"],
      job_description: "Business Analyst (SQL, Tableau, Data Visualization).",
      job_apply_link: "https://careers.swiggy.com",
    },
    {
      employer_name: "MakeMyTrip",
      employer_logo: "",
      employer_website: "https://www.makemytrip.com/careers",
      job_city: "Gurgaon",
      job_employment_types: ["Full-time"],
      job_description:
        "iOS Developer (Swift, UIKit, REST APIs) for travel app.",
      job_apply_link: "https://www.makemytrip.com/careers",
    },
    {
      employer_name: "CRED",
      employer_logo: "",
      employer_website: "https://cred.club/careers",
      job_city: "Bangalore",
      job_employment_types: ["Full-time"],
      job_description: "Data Scientist (Python, ML, Deep Learning, LLMs).",
      job_apply_link: "https://cred.club/careers",
    },
    {
      employer_name: "Delhivery",
      employer_logo: "",
      employer_website: "https://www.delhivery.com/careers",
      job_city: "Gurgaon",
      job_employment_types: ["Full-time"],
      job_description:
        "Operations Manager (Supply Chain, Logistics, Analytics).",
      job_apply_link: "https://www.delhivery.com/careers",
    },
    {
      employer_name: "PhonePe",
      employer_logo: "",
      employer_website: "https://www.phonepe.com/careers",
      job_city: "Bangalore",
      job_employment_types: ["Full-time"],
      job_description:
        "Security Engineer (Pen-testing, Cloud Security, Python).",
      job_apply_link: "https://www.phonepe.com/careers",
    },
    {
      employer_name: "Lenskart",
      employer_logo: "",
      employer_website: "https://careers.lenskart.com",
      job_city: "Gurgaon",
      job_employment_types: ["Full-time"],
      job_description:
        "Digital Marketing Specialist (SEO, Google Ads, Analytics).",
      job_apply_link: "https://careers.lenskart.com",
    },
    {
      employer_name: "Nykaa",
      employer_logo: "",
      employer_website: "https://careers.nykaa.com",
      job_city: "Mumbai",
      job_employment_types: ["Full-time"],
      job_description: "Graphic Designer (Adobe Suite, UI/UX, E-commerce).",
      job_apply_link: "https://careers.nykaa.com",
    },
    {
      employer_name: "Mindtree",
      employer_logo: "",
      employer_website: "https://www.mindtree.com/careers",
      job_city: "Bangalore",
      job_employment_types: ["Full-time"],
      job_description: "Backend Developer (Go, Microservices, Cloud Native).",
      job_apply_link: "https://www.mindtree.com/careers",
    },
    {
      employer_name: "Capgemini",
      employer_logo: "",
      employer_website: "https://www.capgemini.com/in-en/careers",
      job_city: "Pune",
      job_employment_types: ["Full-time"],
      job_description: "Full Stack Developer (Angular, .NET Core, SQL Server).",
      job_apply_link: "https://www.capgemini.com/in-en/careers",
    },
    {
      employer_name: "Zoho",
      employer_logo: "",
      employer_website: "https://www.zoho.com/careers",
      job_city: "Chennai",
      job_employment_types: ["Full-time"],
      job_description: "Web Developer (HTML, CSS, JavaScript, PHP).",
      job_apply_link: "https://www.zoho.com/careers",
    },
    {
      employer_name: "Google India",
      employer_logo: "",
      employer_website: "https://careers.google.com/locations/india/",
      job_city: "Bangalore",
      job_employment_types: ["Full-time"],
      job_description: "AI Research Engineer (ML, NLP, LLMs, Python).",
      job_apply_link: "https://careers.google.com/locations/india/",
    },
    {
      employer_name: "Microsoft India",
      employer_logo: "",
      employer_website: "https://careers.microsoft.com",
      job_city: "Hyderabad",
      job_employment_types: ["Full-time"],
      job_description: "Cloud Solutions Architect (Azure, DevOps, IaC).",
      job_apply_link: "https://careers.microsoft.com",
    },
    {
      employer_name: "Adobe India",
      employer_logo: "",
      employer_website:
        "https://adobe.wd5.myworkdayjobs.com/en-US/external_experienced",
      job_city: "Noida",
      job_employment_types: ["Full-time"],
      job_description: "Frontend Engineer (React, Redux, Webpack).",
      job_apply_link:
        "https://adobe.wd5.myworkdayjobs.com/en-US/external_experienced",
    },
    {
      employer_name: "SAP Labs India",
      employer_logo: "",
      employer_website: "https://jobs.sap.com",
      job_city: "Bangalore",
      job_employment_types: ["Full-time"],
      job_description: "Backend Developer (Java, Spring, Microservices).",
      job_apply_link: "https://jobs.sap.com",
    },
    {
      employer_name: "Oracle India",
      employer_logo: "",
      employer_website: "https://www.oracle.com/in/careers/",
      job_city: "Bangalore",
      job_employment_types: ["Full-time"],
      job_description: "Database Administrator (Oracle DB, PL/SQL, Cloud).",
      job_apply_link: "https://www.oracle.com/in/careers/",
    },
    {
      employer_name: "Deloitte India",
      employer_logo: "",
      employer_website: "https://jobs2.deloitte.com/in/en",
      job_city: "Mumbai",
      job_employment_types: ["Full-time"],
      job_description: "Data Engineer (ETL, Big Data, Spark, Python).",
      job_apply_link: "https://jobs2.deloitte.com/in/en",
    },
    {
      employer_name: "EY India",
      employer_logo: "",
      employer_website: "https://www.ey.com/en_in/careers",
      job_city: "Gurgaon",
      job_employment_types: ["Full-time"],
      job_description: "AI Consultant (ML, Data Science, Python, R).",
      job_apply_link: "https://www.ey.com/en_in/careers",
    },
    {
      employer_name: "KPMG India",
      employer_logo: "",
      employer_website: "https://home.kpmg/in/en/home/careers.html",
      job_city: "Mumbai",
      job_employment_types: ["Full-time"],
      job_description: "Data Analyst (Power BI, SQL, Excel, Python).",
      job_apply_link: "https://home.kpmg/in/en/home/careers.html",
    },
    {
      employer_name: "LTIMindtree",
      employer_logo: "",
      employer_website: "https://www.ltimindtree.com/careers/",
      job_city: "Bangalore",
      job_employment_types: ["Full-time"],
      job_description: "Backend Developer (Node.js, Express, MongoDB).",
      job_apply_link: "https://www.ltimindtree.com/careers/",
    },
    {
      employer_name: "Persistent Systems",
      employer_logo: "",
      employer_website: "https://www.persistent.com/careers/",
      job_city: "Pune",
      job_employment_types: ["Full-time"],
      job_description: "Frontend Developer (Angular, TypeScript, SCSS).",
      job_apply_link: "https://www.persistent.com/careers/",
    },
    {
      employer_name: "Publicis Sapient",
      employer_logo: "",
      employer_website: "https://careers.publicissapient.com/",
      job_city: "Gurgaon",
      job_employment_types: ["Full-time"],
      job_description: "Full Stack Developer (Java, React, AWS).",
      job_apply_link: "https://careers.publicissapient.com/",
    },
    {
      employer_name: "ThoughtWorks",
      employer_logo: "",
      employer_website: "https://www.thoughtworks.com/careers",
      job_city: "Pune",
      job_employment_types: ["Full-time"],
      job_description: "Backend Developer (Ruby, Rails, PostgreSQL).",
      job_apply_link: "https://www.thoughtworks.com/careers",
    },
    {
      employer_name: "PayU",
      employer_logo: "",
      employer_website: "https://corporate.payu.com/careers/",
      job_city: "Gurgaon",
      job_employment_types: ["Full-time"],
      job_description: "Frontend Developer (Vue.js, Nuxt.js, REST APIs).",
      job_apply_link: "https://corporate.payu.com/careers/",
    },
    {
      employer_name: "Razorpay",
      employer_logo: "",
      employer_website: "https://razorpay.com/careers/",
      job_city: "Bangalore",
      job_employment_types: ["Full-time"],
      job_description: "Backend Developer (Go, Microservices, Kafka).",
      job_apply_link: "https://razorpay.com/careers/",
    },
    {
      employer_name: "Meesho",
      employer_logo: "",
      employer_website: "https://meesho.io/careers",
      job_city: "Bangalore",
      job_employment_types: ["Full-time"],
      job_description: "Data Analyst (SQL, Python, Dashboarding).",
      job_apply_link: "https://meesho.io/careers",
    },
    {
      employer_name: "Unacademy",
      employer_logo: "",
      employer_website: "https://unacademy.com/careers",
      job_city: "Bangalore",
      job_employment_types: ["Full-time"],
      job_description: "AI Developer (NLP, LLMs, Python, HuggingFace).",
      job_apply_link: "https://unacademy.com/careers",
    },
    {
      employer_name: "Dream11",
      employer_logo: "",
      employer_website: "https://www.dream11.com/careers",
      job_city: "Mumbai",
      job_employment_types: ["Full-time"],
      job_description: "Full Stack Developer (React, Node.js, AWS).",
      job_apply_link: "https://www.dream11.com/careers",
    },
    {
      employer_name: "Groww",
      employer_logo: "",
      employer_website: "https://groww.in/careers",
      job_city: "Bangalore",
      job_employment_types: ["Full-time"],
      job_description: "Frontend Developer (React, Redux, TypeScript).",
      job_apply_link: "https://groww.in/careers",
    },
    {
      employer_name: "Upstox",
      employer_logo: "",
      employer_website: "https://upstox.com/careers",
      job_city: "Mumbai",
      job_employment_types: ["Full-time"],
      job_description: "Backend Developer (Java, Spring Boot, Kafka).",
      job_apply_link: "https://upstox.com/careers",
    },

    // --- Minimal/Entry-level jobs (basic HTML, CSS, JS, C, Python) ---
    {
      employer_name: "StarterWeb",
      employer_logo: "",
      employer_website: "",
      job_city: "Delhi",
      job_employment_types: ["Full-time"],
      job_description: "Junior Web Developer (HTML, CSS, basic JavaScript).",
      job_apply_link: "#",
    },
    {
      employer_name: "CodeCamp",
      employer_logo: "",
      employer_website: "",
      job_city: "Pune",
      job_employment_types: ["Full-time"],
      job_description: "Intern - Web Assistant (HTML, CSS basics).",
      job_apply_link: "#",
    },
    {
      employer_name: "PyLearn",
      employer_logo: "",
      employer_website: "",
      job_city: "Bangalore",
      job_employment_types: ["Full-time"],
      job_description: "Python Trainee (Basic Python scripting, logic).",
      job_apply_link: "#",
    },
    {
      employer_name: "SimpleScripts",
      employer_logo: "",
      employer_website: "",
      job_city: "Chennai",
      job_employment_types: ["Full-time"],
      job_description: "Junior Programmer (C language basics, logic building).",
      job_apply_link: "#",
    },
    {
      employer_name: "WebLaunch",
      employer_logo: "",
      employer_website: "",
      job_city: "Hyderabad",
      job_employment_types: ["Full-time"],
      job_description: "Intern - Website Editor (HTML, CSS, JS basics).",
      job_apply_link: "#",
    },
    {
      employer_name: "BrightStart",
      employer_logo: "",
      employer_website: "",
      job_city: "Kolkata",
      job_employment_types: ["Full-time"],
      job_description: "Trainee Developer (HTML, CSS, Python basics).",
      job_apply_link: "#",
    },
    {
      employer_name: "ScriptEase",
      employer_logo: "",
      employer_website: "",
      job_city: "Ahmedabad",
      job_employment_types: ["Full-time"],
      job_description: "Junior Scripter (JavaScript, HTML basics).",
      job_apply_link: "#",
    },
    {
      employer_name: "CodeRoots",
      employer_logo: "",
      employer_website: "",
      job_city: "Jaipur",
      job_employment_types: ["Full-time"],
      job_description: "Intern - Programming Assistant (C, Python basics).",
      job_apply_link: "#",
    },
    {
      employer_name: "Tata Consultancy Services",
      employer_logo: "",
      employer_website: "https://www.tcs.com",
      job_city: "Mumbai",
      job_employment_types: ["Full-time"],
      job_description:
        "Frontend Developer (React.js, TypeScript) for enterprise web apps.",
      job_apply_link: "https://www.tcs.com/careers",
    },
    // ...other jobs...

    // --- Minimal/Entry-level jobs (basic HTML, CSS, JS, C, Python) ---
    {
      employer_name: "StarterWeb",
      employer_logo: "",
      employer_website: "",
      job_city: "Delhi",
      job_employment_types: ["Full-time"],
      job_description: "Junior Web Developer (HTML, CSS, basic JavaScript).",
      job_apply_link: "#",
    },
    // ...other minimal jobs...

    // --- Gujarat Jobs ---
    {
      employer_name: "Gujarat Tech Solutions",
      employer_logo: "",
      employer_website: "https://gujarattech.com",
      job_city: "Ahmedabad",
      job_employment_types: ["Full-time"],
      job_description: "Frontend Developer (HTML, CSS, JavaScript, React).",
      job_apply_link: "#",
    },
    {
      employer_name: "Surat WebWorks",
      employer_logo: "",
      employer_website: "",
      job_city: "Surat",
      job_employment_types: ["Full-time"],
      job_description: "Junior Web Designer (HTML, CSS basics).",
      job_apply_link: "#",
    },
    {
      employer_name: "Vadodara IT Hub",
      employer_logo: "",
      employer_website: "",
      job_city: "Vadodara",
      job_employment_types: ["Full-time"],
      job_description: "Python Developer (Basic Python, Django).",
      job_apply_link: "#",
    },
    {
      employer_name: "Rajkot CodeBase",
      employer_logo: "",
      employer_website: "",
      job_city: "Rajkot",
      job_employment_types: ["Full-time"],
      job_description: "Intern - Web Assistant (HTML, CSS, JS basics).",
      job_apply_link: "#",
    },
    {
      employer_name: "Bhavnagar Digital",
      employer_logo: "",
      employer_website: "",
      job_city: "Bhavnagar",
      job_employment_types: ["Full-time"],
      job_description: "Junior Programmer (C, Python basics).",
      job_apply_link: "#",
    },
    {
      employer_name: "TCS iON Digital Learning",
      employer_logo: "",
      employer_website: "https://learning.tcsionhub.in",
      job_city: "Ahmedabad",
      job_employment_types: ["Full-time", "Remote"],
      job_description:
        "Online React Developer for EdTech platform. Work from home, build interactive learning modules.",
      job_apply_link: "https://learning.tcsionhub.in/jobs",
    },
    {
      employer_name: "eInfochips (An Arrow Company)",
      employer_logo: "",
      employer_website: "https://www.einfochips.com",
      job_city: "Ahmedabad",
      job_employment_types: ["Full-time", "Remote"],
      job_description: "Remote Node.js Backend Developer for IoT solutions.",
      job_apply_link: "https://www.einfochips.com/careers/",
    },
    {
      employer_name: "Tatvasoft",
      employer_logo: "",
      employer_website: "https://www.tatvasoft.com",
      job_city: "Ahmedabad",
      job_employment_types: ["Full-time", "Remote"],
      job_description: "Online Python Developer for global SaaS projects.",
      job_apply_link: "https://www.tatvasoft.com/careers/",
    },
    {
      employer_name: "Gateway Group",
      employer_logo: "",
      employer_website: "https://www.gatewaydigital.com",
      job_city: "Ahmedabad",
      job_employment_types: ["Full-time", "Remote"],
      job_description:
        "Remote AWS Cloud Engineer for digital transformation projects.",
      job_apply_link: "https://www.gatewaydigital.com/careers/",
    },
    {
      employer_name: "Simform",
      employer_logo: "",
      employer_website: "https://www.simform.com",
      job_city: "Ahmedabad",
      job_employment_types: ["Full-time", "Remote"],
      job_description:
        "Online Full Stack Developer (React, Node.js) for US clients.",
      job_apply_link: "https://www.simform.com/careers/",
    },
    {
      employer_name: "Radixweb",
      employer_logo: "",
      employer_website: "https://radixweb.com",
      job_city: "Ahmedabad",
      job_employment_types: ["Full-time", "Remote"],
      job_description:
        "Remote Python/Django Developer for enterprise automation.",
      job_apply_link: "https://radixweb.com/careers",
    },
    {
      employer_name: "Knovator Technologies",
      employer_logo: "",
      employer_website: "https://www.knovator.com",
      job_city: "Surat",
      job_employment_types: ["Full-time", "Remote"],
      job_description: "Online React.js Developer for healthcare SaaS.",
      job_apply_link: "https://www.knovator.com/careers/",
    },
    {
      employer_name: "WebOccult Technologies",
      employer_logo: "",
      employer_website: "https://weboccult.com",
      job_city: "Ahmedabad",
      job_employment_types: ["Full-time", "Remote"],
      job_description: "Remote AWS DevOps Engineer for cloud migration.",
      job_apply_link: "https://weboccult.com/careers/",
    },
    {
      employer_name: "Yudiz Solutions",
      employer_logo: "",
      employer_website: "https://www.yudiz.com",
      job_city: "Ahmedabad",
      job_employment_types: ["Full-time", "Remote"],
      job_description:
        "Online Python Developer for gaming and blockchain projects.",
      job_apply_link: "https://www.yudiz.com/careers/",
    },
    {
      employer_name: "Prismetric",
      employer_logo: "",
      employer_website: "https://www.prismetric.com",
      job_city: "Gandhinagar",
      job_employment_types: ["Full-time", "Remote"],
      job_description: "Remote React Native Developer for mobile apps.",
      job_apply_link: "https://www.prismetric.com/careers/",
    },
    {
      employer_name: "OpenXcell",
      employer_logo: "",
      employer_website: "https://www.openxcell.com",
      job_city: "Ahmedabad",
      job_employment_types: ["Full-time", "Remote"],
      job_description: "Online Node.js Developer for fintech platforms.",
      job_apply_link: "https://www.openxcell.com/careers/",
    },
    {
      employer_name: "Sapphire Software Solutions",
      employer_logo: "",
      employer_website: "https://www.sapphiresolutions.net",
      job_city: "Ahmedabad",
      job_employment_types: ["Full-time", "Remote"],
      job_description: "Remote Python Developer for AI/ML projects.",
      job_apply_link: "https://www.sapphiresolutions.net/careers/",
    },
    {
      employer_name: "Techuz Infoweb",
      employer_logo: "",
      employer_website: "https://www.techuz.com",
      job_city: "Ahmedabad",
      job_employment_types: ["Full-time", "Remote"],
      job_description: "Online React.js Developer for US-based clients.",
      job_apply_link: "https://www.techuz.com/careers/",
    },
    {
      employer_name: "Elsner Technologies",
      employer_logo: "",
      employer_website: "https://www.elsner.com",
      job_city: "Ahmedabad",
      job_employment_types: ["Full-time", "Remote"],
      job_description: "Remote AWS Cloud Engineer for e-commerce solutions.",
      job_apply_link: "https://www.elsner.com/careers/",
    },
    {
      employer_name: "Logicwind",
      employer_logo: "",
      employer_website: "https://www.logicwind.com",
      job_city: "Surat",
      job_employment_types: ["Full-time", "Remote"],
      job_description: "Online Full Stack Developer (React, Node.js, AWS).",
      job_apply_link: "https://www.logicwind.com/careers/",
    },
    {
      employer_name: "Space-O Technologies",
      employer_logo: "",
      employer_website: "https://www.spaceotechnologies.com",
      job_city: "Ahmedabad",
      job_employment_types: ["Full-time", "Remote"],
      job_description: "Remote Python Developer for mobile and web apps.",
      job_apply_link: "https://www.spaceotechnologies.com/careers/",
    },
  ];
  res.send(demoJobs);
});

app.listen(port, () => {
  console.log(`http://localhost:${port}`);
});
